ersion: 0.0
os: linux
files:
- source: /
  destination: /usr/my-diet-node
  overwrite: true
permissions:
- object: /usr/my-diet-node/config/codedeploy
  pattern: "*.sh"
  owner: root
  group: root
  mode: 755
  type:
  - file
hooks:
  BeforeInstall:
  - location: config/codedeploy/install_dependencies.sh
    timeout: 180
  ApplicationStart:
  - location: config/codedeploy/start_server.sh
    timeout: 180
  ApplicationStop:
  - location: config/codedeploy/stop_server.sh
    timeout: 180
  ValidateService:
  - location: config/codedeploy/validate_service.sh
    timeout: 180