version: 0.0
os: linux
files:
- source: /
  destination: /usr/mydiet-user-node
  overwrite: true
permissions:
- object: /usr/mydiet-user-node/scripts/codedeploy
  pattern: "*.sh"
  owner: root
  group: root
  mode: 755
  type:
  - file
hooks:
  BeforeInstall:
  - location: scripts/codedeploy/install_dependencies.sh
    timeout: 180
  ApplicationStart:
  - location: scripts/codedeploy/start_server.sh
    timeout: 180
    runas: ec2-user
  ApplicationStop:
  - location: scripts/codedeploy/stop_server.sh
    timeout: 180
    runas: ec2-user
  ValidateService:
  - location: scripts/codedeploy/validate_service.sh
    timeout: 180
    runas: ec2-user