version: 0.0
os: linux
files:
- source: /
  destination: /usr/my-diet-node
  overwrite: true
permissions:
- object: /usr/my-diet-node
  owner: ec2-user
  group: adm
  mode: 766
  type:
  - directory
- object: /usr/my-diet-node/scripts/codedeploy
  pattern: "*.sh"
  owner: ec2-user
  group: adm
  mode: 755
  type:
  - file
hooks:
  BeforeInstall:
  - location: scripts/codedeploy/install_dependencies.sh
    timeout: 180
  ApplicationStart:
  - location: scripts/codedeploy/start_server.sh
    timeout: 180
  ApplicationStop:
  - location: scripts/codedeploy/stop_server.sh
    timeout: 180
  ValidateService:
  - location: scripts/codedeploy/validate_service.sh
    timeout: 180